# Generated by Django 3.2.8 on 2021-11-26 15:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cedula_de_identidad', models.IntegerField(help_text='Para todo usuario es el numero de c.i.', primary_key=True, serialize=False, verbose_name='c.i.')),
                ('rol', models.CharField(blank=True, choices=[('usuario', 'usuario'), ('farmacia', 'farmacia'), ('medico', 'medico'), ('stock', 'stock')], default='usuario', max_length=100, null=True)),
                ('usuario', models.CharField(max_length=100, unique=True, verbose_name='Nombre de usuario')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_activo', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_de_nacimiento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha de nacimiento')),
                ('departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(2147483646)])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['usuario'],
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principio_activo', models.CharField(default='----', max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('vencimiento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha de vencimiento')),
                ('estado', models.CharField(choices=[('RES', 'Reservado'), ('RET', 'Retirado')], default='RES', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['paciente'],
            },
        ),
    ]
