# Generated by Django 3.2.8 on 2021-11-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='estado',
            field=models.CharField(choices=[('RES', 'Reservado'), ('RET', 'Retirado')], default='RES', max_length=50),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='principio_activo',
            field=models.CharField(default='----', max_length=100),
        ),
    ]
