# Generated by Django 3.2 on 2021-11-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetas',
            name='cronico',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
