# Generated by Django 3.2.8 on 2021-11-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.IntegerField(blank=True, max_length=9, null=True),
        ),
    ]
