# Generated by Django 3.2 on 2021-11-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0003_alter_recetas_cronico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='cronico',
            field=models.BooleanField(default=False),
        ),
    ]
