# Generated by Django 3.2 on 2021-12-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0004_alter_recetas_cronico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(blank=True, choices=[('usuario', 'usuario'), ('farmacia', 'farmacia'), ('medico', 'medico'), ('stock', 'stock'), ('administrador', 'administrador')], default='usuario', max_length=100, null=True),
        ),
    ]
