# Generated by Django 3.2.8 on 2021-11-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0009_alter_usuarios_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(blank=True, choices=[('USU', 'usuario'), ('FAR', 'farmacia'), ('MED', 'medico'), ('STO', 'stock')], max_length=100, null=True),
        ),
    ]
