# Generated by Django 3.2.8 on 2021-11-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0011_alter_usuarios_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(blank=True, choices=[('usuario', 'usuario'), ('farmacia', 'farmacia'), ('medico', 'medico'), ('stock', 'stock')], default='usuario', max_length=100, null=True),
        ),
    ]
