# Generated by Django 3.2.8 on 2021-11-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0013_alter_usuarios_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_de_nacimiento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
