# Generated by Django 3.2.8 on 2021-11-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0014_alter_usuarios_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='vencimiento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha de vencimiento'),
        ),
    ]
