# Generated by Django 3.2.7 on 2021-10-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.ImageField(upload_to='')),
                ('vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('laboratorio', models.CharField(max_length=100)),
                ('principio_activo', models.CharField(max_length=200)),
                ('forma', models.CharField(max_length=50)),
                ('contraindicaciones', models.CharField(max_length=500)),
            ],
        ),
    ]
