# Generated by Django 3.2.7 on 2021-10-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmacias',
            name='departamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
