# Generated by Django 3.2.8 on 2021-11-12 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionStock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacias',
            name='funcionarios',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Funcionarios'),
        ),
    ]
