# Generated by Django 3.2.7 on 2021-10-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0002_alter_farmacias_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotes',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='contraindicaciones',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='forma',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
