# Generated by Django 3.2.7 on 2021-10-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0003_auto_20211009_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentos',
            name='categoria',
            field=models.CharField(max_length=50, verbose_name='Categoria(venta libre, receta verde o FNR)'),
        ),
    ]
