# Generated by Django 3.2.7 on 2021-10-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0004_alter_medicamentos_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotes',
            name='ingreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
