# Generated by Django 3.2.8 on 2021-10-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0007_farmacias_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmacias',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lotes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
