# Generated by Django 3.2.8 on 2021-10-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0008_auto_20211020_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentos',
            name='categoria',
            field=models.CharField(blank=True, choices=[('VL', 'Venta Libre'), ('RV', 'Receta Verde'), ('FNR', 'Fondo Nacional De Recursos')], max_length=50, null=True, verbose_name='Categoria(venta libre, receta verde o FNR)'),
        ),
    ]
