# Generated by Django 3.2.8 on 2021-10-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0009_alter_medicamentos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmacias',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='contraindicaciones',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='laboratorio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='principio_activo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
