# Generated by Django 3.2.8 on 2021-10-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0010_auto_20211023_0900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmacias',
            options={'ordering': ['nombre'], 'verbose_name': 'Farmacia', 'verbose_name_plural': 'Farmacias'},
        ),
        migrations.AlterModelOptions(
            name='lotes',
            options={'ordering': ['stock'], 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.AlterModelOptions(
            name='medicamentos',
            options={'ordering': ['nombre_comercial'], 'verbose_name': 'Medicamento', 'verbose_name_plural': 'Medicamentos'},
        ),
    ]
