# Generated by Django 3.2.8 on 2021-11-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0011_auto_20211023_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotes',
            name='vencimiento',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Fecha de vencimiento'),
        ),
    ]
