# Generated by Django 3.2.8 on 2021-11-05 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionStock', '0013_alter_lotes_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacias',
            name='funcionarios',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Funcionarios'),
        ),
    ]
